apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-streams-index-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-streams-index-router
  template:
    metadata:
      labels:
        app: kafka-streams-index-router
    spec:
      containers:
      - name: kafka-streams-index-router
        image: your-docker-repo/kafka-streams-index-router:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-streams-index-router
spec:
  selector:
    app: kafka-streams-index-router
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9092
