apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-streams-index-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-streams-index-router
  template:
    metadata:
      labels:
        app: kafka-streams-index-router
    spec:
      containers:
      - name: kafka-streams-index-router
        image: your-repo/kafka-streams-index-router:latest
        envFrom:
        - configMapRef:
            name: kafka-streams-config
        - secretRef:
            name: splunk-secret
